### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by akiwieh** [jpartemis/cwarp#1]
Error when attempting to run on a PC, win10, Chrome

![image](https://user-images.githubusercontent.com/85299582/120661892-aa666180-c456-11eb-97ea-b5ccfa53d24f.png)

**Comment by jpartemis** [comment]
Streamlit sharing is an alpha product we've found the server they are provisioning for the app is dying occasionally. It's not really a code issue. After being rebooted (which I just did), it's fine (fine as of june 3, 1030am est... give it a try!). Until Streamlit figures out their cloud servers, one easy work around is to run it for yourself. 

Prereqs: Working python3.6+ with pip
- download the files. 
- In any python environment which has pip simply install: 
pandas, numpy, matplotlib, seaborn, yfinance, and streamlit  
(on linux "sudo pip3 install pandas" in a terminal.) 
- then simply: "streamlit run cwarp_app.py"

This will open the app on your local machine.
